name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  security-events: write

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-frontend

jobs:
  ci-cd:
    name: Full CI/CD Pipeline (Multi-Arch)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/backend/Dockerfile
          ignore: DL3008,DL3009,DL3018,DL3059
          failure-threshold: warning

      - name: Lint Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/frontend/Dockerfile
          ignore: DL3008,DL3009,DL3018,DL3059
          failure-threshold: warning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Backend metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BACKEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push Backend Multi-Arch
        uses: docker/build-push-action@v5
        with:
          context: app/backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,name=backend-cache
          cache-to: type=gha,mode=max,name=backend-cache

      - name: Test Backend container (amd64)
        run: |
          docker run -d --name test-backend -p 8000:8000 ${{ env.BACKEND_IMAGE }}:latest
          echo "Waiting for backend to be ready..."
          for i in {1..15}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/api/greeting || echo "000")
            if [ "$STATUS" == "200" ]; then
              echo "Backend ready!"
              break
            fi
            sleep 2
          done
          docker logs test-backend
          docker stop test-backend
          docker rm test-backend

      - name: Trivy scan - Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}:latest
          format: sarif
          output: backend-trivy-results.sarif
          severity: CRITICAL,HIGH
        continue-on-error: true

      - name: Upload Backend Trivy results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: backend-trivy-results.sarif
          category: backend-container

      - name: Extract Frontend metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push Frontend Multi-Arch
        uses: docker/build-push-action@v5
        with:
          context: app/frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,name=frontend-cache
          cache-to: type=gha,mode=max,name=frontend-cache

      - name: Test Frontend container (amd64)
        run: |
          docker run -d --name test-frontend -p 80:80 ${{ env.FRONTEND_IMAGE }}:latest
          echo "Waiting for frontend to be ready..."
          for i in {1..15}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/ || echo "000")
            if [ "$STATUS" == "200" ]; then
              echo "Frontend ready!"
              break
            fi
            sleep 2
          done
          docker logs test-frontend
          docker stop test-frontend
          docker rm test-frontend

      - name: Trivy scan - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:latest
          format: sarif
          output: frontend-trivy-results.sarif
          severity: CRITICAL,HIGH
        continue-on-error: true

      - name: Upload Frontend Trivy results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: frontend-trivy-results.sarif
          category: frontend-container

      - name: Job Summary
        run: |
          echo "## CI/CD Multi-Arch Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Backend Images:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta-backend.outputs.tags }}' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Frontend Images:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta-frontend.outputs.tags }}' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All images tested, scanned, and ready for deployment!" >> $GITHUB_STEP_SUMMARY