name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  security-events: write

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-frontend

jobs:
  lint-dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Lint Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/backend/Dockerfile
          ignore: DL3008,DL3009,DL3018
          failure-threshold: warning
      
      - name: Lint Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/frontend/Dockerfile
          ignore: DL3008,DL3009,DL3018
          failure-threshold: warning

  build-test-scan:
    name: Build, Test and Scan Images
    runs-on: ubuntu-latest
    needs: lint-dockerfiles
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend image (multi-platform, local)
        uses: docker/build-push-action@v5
        with:
          context: app/backend
          push: false
          tags: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Test Backend container
        run: |
          docker run -d --name test-backend -e NODE_ENV=production -e API_PORT=8000 -p 8000:8000 ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          sleep 10
          timeout 30 bash -c 'until curl -f http://localhost:8000/api/greeting; do echo "Waiting for backend..."; sleep 2; done'
          echo "Backend test successful"
          docker stop test-backend
          docker rm test-backend

      - name: Run Trivy scan - Backend
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          format: 'sarif'
          output: 'backend-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Upload Backend Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'backend-trivy-results.sarif'
          category: 'backend-container'

      - name: Build Frontend image (multi-platform, local)
        uses: docker/build-push-action@v5
        with:
          context: app/frontend
          push: false
          tags: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Test Frontend container
        run: |
          docker run -d --name test-frontend -p 3000:3000 ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          sleep 10
          timeout 30 bash -c 'until curl -f http://localhost:3000/health; do echo "Waiting for frontend..."; sleep 2; done'
          echo "Frontend test successful"
          docker stop test-frontend
          docker rm test-frontend

      - name: Run Trivy scan - Frontend
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          format: 'sarif'
          output: 'frontend-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Upload Frontend Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'frontend-trivy-results.sarif'
          category: 'frontend-container'

  publish:
    name: Publish Images to Docker Hub
    runs-on: ubuntu-latest
    needs: build-test-scan
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Backend metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BACKEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Backend image
        uses: docker/build-push-action@v5
        with:
          context: app/backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Frontend metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: app/frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Job Summary
        run: |
          echo "## Published Images" >> $GITHUB_STEP_SUMMARY
          echo "Backend Tags:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta-backend.outputs.tags }}' >> $GITHUB_STEP_SUMMARY
          echo "Frontend Tags:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta-frontend.outputs.tags }}' >> $GITHUB_STEP_SUMMARY