apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-app.fullname" . }}-backend
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "portfolio-app.name" . }}-backend