apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-app.fullname" . }}-frontend
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "portfolio-app.name" . }}-frontend