apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-app.fullname" . }}-frontend
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "portfolio-app.name" . }}-frontend
