apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-app.fullname" . }}-nginx
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "portfolio-app.name" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "portfolio-app.name" . }}-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "portfolio-app.fullname" . }}-nginx-config
            defaultMode: 0644