apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portfolio-app.fullname" . }}-nginx-config
  labels:
    {{- include "portfolio-app.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream frontend {
        server {{ include "portfolio-app.fullname" . }}-frontend:80 max_fails=3 fail_timeout=30s;
    }

    upstream backend {
        server {{ include "portfolio-app.fullname" . }}-backend:8000 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 80;
        server_name localhost;
        
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }